import { z } from "zod";
import rawSizes from "./image-dimensions.json" with { type: "json" };

/**
 * JPEG-only WebP sidecar mapping. Pure string transformation, no
 * filesystem access: every internal JPEG under a root-relative path
 * has a same-name `.webp` sidecar by repository invariant (see
 * `npm run images`). PNG, SVG, external, protocol-relative, and
 * relative sources are out of scope and map to `undefined`.
 */
export function isInternalJpeg(src: string): boolean {
	if (src.startsWith("//")) {
		return false;
	}
	if (!src.startsWith("/")) {
		return false;
	}
	const lower = src.toLowerCase();
	return lower.endsWith(".jpg") || lower.endsWith(".jpeg");
}

/**
 * Map an internal JPEG source to its required WebP sidecar.
 * Returns `undefined` for anything out of scope (PNG, SVG, WebP,
 * external, protocol-relative, relative). Never touches the disk.
 */
export function webpSrc(src: string): string | undefined {
	if (!isInternalJpeg(src)) {
		return undefined;
	}
	return src.replace(/\.(jpe?g)$/i, ".webp");
}

export interface ImageSize {
	width: number;
	height: number;
}

const SizeTableSchema = z.record(
	z.string(),
	z.object({
		width: z.number().int().positive(),
		height: z.number().int().positive(),
	}),
);

/**
 * Pixel sizes of every shipped image, keyed by site path. Generated by
 * `npm run images` and kept current by `npm run images:check`, so the
 * lookup here is a pure table read.
 */
const SIZES = SizeTableSchema.parse(rawSizes);

/**
 * Pixel size of an internal image, or `undefined` when the source is
 * external, relative, or ships no image. Callers emit `width`/`height`
 * from it so the browser reserves the box before the bytes arrive.
 */
export function imageSize(src: string): ImageSize | undefined {
	return SIZES[src];
}
