import { z } from "zod";
import rawSizes from "./image-dimensions.json" with { type: "json" };

/**
 * Whether a source is a JPEG shipped by this site: a root-relative
 * `.jpg`/`.jpeg` path. Only these sources get responsive renditions.
 * PNG, SVG, WebP, external, protocol-relative, and relative sources
 * are out of scope. Pure string test, no filesystem access.
 */
export function isInternalJpeg(src: string): boolean {
	if (src.startsWith("//")) {
		return false;
	}
	if (!src.startsWith("/")) {
		return false;
	}
	const lower = src.toLowerCase();
	return lower.endsWith(".jpg") || lower.endsWith(".jpeg");
}

/**
 * Site path of the rendered cover art for a piece with no `cover`.
 * Generated by `npm run images`; `images:check` guarantees the file
 * exists for every published coverless piece.
 */
export function placeholderSrc(slug: string): string {
	return `/img/placeholders/${slug}.jpg`;
}

export interface ImageSize {
	width: number;
	height: number;
}

const SizeTableSchema = z.record(
	z.string(),
	z.object({
		width: z.number().int().positive(),
		height: z.number().int().positive(),
	}),
);

/**
 * Pixel sizes of every shipped image, keyed by site path. Generated by
 * `npm run images` and kept current by `npm run images:check`, so the
 * lookup here is a pure table read.
 */
const SIZES = SizeTableSchema.parse(rawSizes);

/**
 * Pixel size of an internal image, or `undefined` when the source is
 * external, relative, or ships no image. Callers emit `width`/`height`
 * from it so the browser reserves the box before the bytes arrive.
 */
export function imageSize(src: string): ImageSize | undefined {
	return SIZES[src];
}
